name: quantum
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - sympy
  - matplotlib
  - seaborn
  - pandas
  - jupyterlab
  - pytest
  - pip
  - pip:
      - cirq
      - qiskit
      - pylint
